export const experience = [
  {
    id: 1,
    company: "Varnion Technology",
    image: "images.jpeg",
    position: "Fullstack Engineer",
    type: "Fulltime",
    duration: "Oct 2020 - Present",
  },
  {
    id: 2,
    company: "Sariraya.co.,Ltd ",
    image: "logo.png",
    position: "Fullstack Engineer",
    type: "Internship",
    duration: "Apr 2023 - Aug 2023",
  },
  {
    id: 3,
    company: "Indonesian Ministry of Industry  ",
    image: "Flag_of_the_Ministry_of_Industry_of_the_Republic_of_Indonesia.svg.png",
    position: "Fullstack Engineer",
    type: "Freelance",
    duration: "Jan 2023 - Jul 2023",
  },
  {
    id: 4,
    company: "Solve On Technology  ",
    image: "adinusa_teknologi_logo.jpeg",
    position: "Fullstack Engineer",
    type: "Contract",
    duration: "Jun 2022 - Sep 2022",
  },
  {
    id: 5,
    company: "Indi Technology  ",
    image: "inditechno_logo.jpeg",
    position: "Product Development",
    type: "Internship",
    duration: "Sep 2022 - Dec 2023",
  },
];
export const Projects = [
  {
    id: 1,
    name: "Varnion website builder",
    technology: [
      "React",
      "Node JS",
      "Express JS",
      "Prisma",
      "MySQL",
      "Vite JS",
      "nginx",
      "Tailwind CSS",
      "PostgreSQL",
      "RabbitMQ",
      "Docker",
      "GCP",
      "Cloudflare",
    ],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://production.varnion.tech/login",
    github: "",
    gitlab: "",
  },
  {
    id: 2,
    name: "Fiberzone Website",
    technology: ["GO", "GIN", "MySQL", "Docker", "Iforte Pay", "Firebase", "RabbitMQ", "POSTMAN", "VUE JS", "Flutter", "PHP"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    github: "",
    gitlab: "",
  },
  {
    id: 3,
    name: "Fiberzone Supper Apps",
    technology: ["GO", "GIN", "MySQL", "Docker", "Iforte Pay", "Firebase", "RabbitMQ", "POSTMAN", "VUE JS", "Flutter", "PHP"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    github: "",
    gitlab: "",
  },
  {
    id: 4,
    name: "Apkita Mobile Website",
    technology: ["Laravel", "React Native", "Fonnte", "MySQL", "Firebase", "Xendit"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    github: "",
    gitlab: "",
  },
  {
    id: 5,
    name: "Apkita Website",
    technology: ["Laravel", "React JS", "Vite", "Redux", "MySQL", "Xendit", "Fonnte"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    github: "",
    gitlab: "",
  },
  {
    id: 6,
    name: "Varnion.net.id",
    technology: ["Next JS", "Zustand"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    github: "",
    gitlab: "",
  },
  {
    id: 7,
    name: "LMS Digitrain Website",
    technology: ["Laravel", "MySQL", "Docker", "Next JS"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    github: "",
    gitlab: "",
  },
  {
    id: 8,
    name: "Japanhalal.net",
    technology: ["Laravel", "MySQL", "Next JS"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    github: "",
    gitlab: "",
  },
  {
    id: 9,
    name: "Sariraya Backoffice",
    technology: ["Laravel", "MySQL"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    github: "",
    gitlab: "",
  },
  {
    id: 10,
    name: "Indonesia Forum",
    technology: [],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    github: "",
    gitlab: "",
  },
];
