export const experience = [
  {
    id: 1,
    company: "Varnion Technology",
    image: "images.jpeg",
    position: "Fullstack Engineer",
    type: "Fulltime",
    duration: "Oct 2023 - Present",
  },
  {
    id: 2,
    company: "Sariraya.co.,Ltd ",
    image: "logo.png",
    position: "Fullstack Engineer",
    type: "Internship",
    duration: "Apr 2023 - Aug 2023",
  },
  {
    id: 3,
    company: "Indonesian Ministry of Industry  ",
    image: "Flag_of_the_Ministry_of_Industry_of_the_Republic_of_Indonesia.svg.png",
    position: "Fullstack Engineer",
    type: "Freelance",
    duration: "Jan 2023 - Jul 2023",
  },
  {
    id: 4,
    company: "Solve On Technology  ",
    image: "adinusa_teknologi_logo.jpeg",
    position: "Fullstack Engineer",
    type: "Contract",
    duration: "Jun 2022 - Sep 2022",
  },
  {
    id: 5,
    company: "Indi Technology  ",
    image: "inditechno_logo.jpeg",
    position: "Product Development",
    type: "Internship",
    duration: "Sep 2022 - Dec 2023",
  },
];
export const projects = [
  {
    id: 1,
    name: "Varnion website builder",
    description: "Varnion is a website builder that allows users to easily create and manage their own websites without the need for coding skills.",
    technologies: [
      "React",
      "Node JS",
      "Express JS",
      "Prisma",
      "MySQL",
      "Vite JS",
      "nginx",
      "Tailwind CSS",
      "PostgreSQL",
      "RabbitMQ",
      "Docker",
      "GCP",
      "Cloudflare",
    ],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://production.varnion.tech/login",
    git: "",
  },
  {
    id: 2,
    name: "Fiberzone Website",
    description:
      "Fiberzone is an e-commerce site that provides internet subscription services with various packages according to customer needs, making it easy for users to choose and manage their subscriptions online.",
    technologies: ["GO", "GIN", "MySQL", "Docker", "Iforte Pay", "Firebase", "RabbitMQ", "POSTMAN", "VUE JS", "Flutter", "PHP"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://www.fiberzone.id/",
    git: "",
  },
  {
    id: 3,
    name: "Fiberzone Supper Apps",
    description:
      "Fiberzone Super Apps is an innovative e-commerce platform that integrates various shopping, payment, and delivery services in one app. With a user-friendly interface, Fiberzone makes it easy for users to find products, pay for internet subscriptions, transact securely, and enjoy a fast and efficient shopping experience.",
    technologies: ["GO", "GIN", "MySQL", "Docker", "Iforte Pay", "Firebase", "RabbitMQ", "POSTMAN", "VUE JS", "Flutter", "PHP"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://github.com/its-rajesh/Retro-Grid",
    git: "",
  },
  {
    id: 4,
    name: "Apkita Mobile",
    description:
      "Apkita Mobile is a community payment management application designed to make it easier for members to manage financial transactions, communicate, and get the latest information efficiently, all in one user-friendly platform.",
    technologies: ["Laravel", "React Native", "Fonnte", "MySQL", "Firebase", "Xendit", "Doku"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://play.google.com/store/apps/details?id=com.icare.apkita&pcampaignid=web_share",
    git: "",
  },
  {
    id: 5,
    name: "Apkita Website",
    description:
      "Apkita Website is a community payment management application designed to make it easier for members to manage financial transactions, communicate, and get the latest information efficiently, all in one user-friendly platform.",
    technologies: ["Laravel", "React JS", "Vite", "Redux", "MySQL", "Xendit", "Fonnte", "Doku"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://app.apkita.id/login?redirect=%2F",
    git: "",
  },
  {
    id: 6,
    name: "Varnion.net.id",
    description:
      "Varnion.net.id is the official website of Varnion Teknologi, a leading ISP provider in Indonesia, offering superior services such as internet infrastructure, infrastructure management, and leading provider solutions. Find the latest information about our services, projects, and professional team here.",
    technologies: ["Next JS", "Zustand"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://www.varnion.net.id/",
    git: "",
  },
  {
    id: 7,
    name: "LMS Digitrain Website",
    description:
      "Digitrain's LMS is an online learning platform designed to provide an interactive and effective learning experience, offering a variety of quality courses and training materials in technology and digital skills. With a user-friendly interface, students can access content at any time, interact with teachers, and follow their learning progress in real-time.",
    technologies: ["Laravel", "MySQL", "Docker", "Next JS"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://digitrain.b4t.go.id/login",
    git: "",
  },
  {
    id: 8,
    name: "Japanhalal.net",
    description:
      "Japanhalal.net is an e-commerce platform that brings quality halal products from Japan, ranging from food and daily necessities. We are committed to providing the best selection that complies with halal standards, so that customers can shop with comfort and confidence. ",
    technologies: ["Laravel", "MySQL", "Next JS"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://www.japanhalal.net/",
    git: "",
  },
  {
    id: 9,
    name: "Sariraya Backoffice",
    description:
      "Sariraya Backoffice is an integrated warehouse management solution designed to simplify inventory management, order processing, and product distribution. With efficient systems and the latest technology, we help businesses improve productivity and accuracy, so they can focus on growth and better customer service.",
    technologies: ["Laravel", "MySQL"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://sariraya.web.id/",
    git: "",
  },
  {
    id: 10,
    name: "Indonesia Forum",
    description:
      "Indonesia Forum is an online community platform that provides a space for discussion, information sharing, and collaboration between users from various backgrounds. With a wide range of topics covering hobbies, technology, and social issues, we encourage constructive interaction and networking between members to enrich shared knowledge and experience.",
    technologies: [],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://indonesiaforum.id/",
    git: "",
  },
  {
    id: 10,
    name: "Apkita Admin Website",
    technologies: ["Laravel", "React JS", "Vite", "Redux", "MySQL", "Xendit", "Fonnte", "Doku"],
    description:
      "Apkita Admin is an application management website specifically designed to make community management easier, providing efficient tools to monitor member activity, manage content, and communicate effectively. With an intuitive interface, Apkita Admin helps community administrators increase engagement and collaboration within the community in an easy and organized manner.",
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://admin.apkita.id/",
    git: "",
  },
  {
    id: 11,
    name: "BPR Purwakarta Website",
    technologies: ["Laravel", "React JS", "MySQL"],
    description:
      "The BPR Purwakarta company profile website development project aims to introduce the vision, mission, and services offered by the financial institution to the wider community, while providing transparent and accessible information about banking products, including deposits, loans, and other financial programs. With an attractive design and user-friendly navigation, this website is expected to increase brand awareness and make it easier for customers and prospective customers to find the information they need, so that BPR Purwakarta can continue to grow and make a positive contribution to the local economy.",
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "http://www.bprpurwakarta.co.id/",
    git: "",
  },
  {
    id: 11,
    name: "Multipliar Website",
    technologies: ["Laravel", "MySQL"],
    description:
      "The profile website project for Multipilar Teknologi aims to showcase the innovations and technology solutions offered by the company, as well as provide a clear overview of its services, flagship projects, and the expertise of the professional team that supports them. With a modern and responsive design, the website is expected to attract the attention of potential clients and business partners, while providing comprehensive information about the company's vision and mission in delivering technology that supports digital transformation. Through this platform, Multipilar Teknologi aims to strengthen its position as a leader in the technology industry, as well as build trust and closer relationships with customers.",
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://www.multipilarbalantika.co.id/",
    git: "",
  },
  {
    id: 12,
    name: "Vixqu",
    description: "Vixqu is a website builder that allows users to easily create and manage their own websites without the need for coding skills.",
    technologies: [
      "React",
      "Node JS",
      "Express JS",
      "Prisma",
      "MySQL",
      "Vite JS",
      "nginx",
      "Tailwind CSS",
      "PostgreSQL",
      "RabbitMQ",
      "Docker",
      "GCP",
      "Cloudflare",
    ],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://development.varnion.my.id/login?redirect=%2F",
    git: "",
  },
  {
    id: 13,
    name: "Vlepo ID",
    description:
      "Vlepo ID presents an intelligent TV management solution that enables efficient and centralized management of television sets. With the latest technology, the system offers complete control over content settings, broadcast schedules, and real-time monitoring of TV performance. Designed for businesses and institutions that need to manage a large number of TVs, Vlepo ID allows you to improve viewing experience and operational efficiency with one easy-to-use platform.",
    technologies: ["Next JS"],
    image: "https://github.com/its-rajesh/Retro-Grid/blob/main/retro-grid.png?raw=true",
    url: "https://vlepo.id/",
    git: "",
  },
];
